spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/cah}
    username: ${DATABASE_USERNAME:cah}
    password: ${DATABASE_PASSWORD:cah}