drop table if exists black_cards cascade;
create table black_cards(
    id     int  generated by default as identity primary key,
    blanks int  not null check(blanks > 0),
    text   text not null unique
);