drop table if exists games;
drop table if exists players;

create table games
(
    id               int generated by default as identity primary key,
    guild_id         bigint not null,
    channel_id       bigint not null,
    message_id       bigint,
    black_card_id    int,
    judge_id         int,
    used_white_cards int[] not null,
    used_black_cards int[] not null
);

create table players
(
    id                     int generated by default as identity primary key,
    user_id                bigint not null,
    game_id                int    not null,
    selected_white_card_id int,
    score                  int default 0
);

alter table games
    add constraint fk_judge_id foreign key (judge_id) references players (id);
alter table players
    add constraint fk_game_id foreign key (game_id) references games (id);
alter table players
    add constraint fk_selected_white_card_id foreign key (selected_white_card_id) references white_cards (id);
